### ISSUE TITLE
关于打包新 Docker 镜像

### ISSUE THREAD

**Issue by wi1dcard** [hustcc/lint-md#45]
遇到一问题，报错如下：

```
internal/modules/cjs/loader.js:236
      throw err;
      ^

Error: Cannot find module '/usr/local/lint-md/node_modules/ast-plugin/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:612:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lint-md/packages/lint-md/lib/lint.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/local/lint-md/node_modules/ast-plugin/package.json',
  requestPath: 'ast-plugin'
}
```

基本复现步骤：

```bash
cd lint-md
yarn install
cd packages/lint-md
yarn run build
cd ../lint-md-cli
bin/index.js
```

环境：

```bash
/usr/local/lint-md/packages/lint-md # yarn -v
1.16.0
/usr/local/lint-md/packages/lint-md # node -v
v12.6.0
```

**Comment by hustcc** [comment]
需要到 ast plugin 和 lint-md 分别运行 yarn build。
