### ISSUE TITLE
Windows 环境下的通配符错误

### ISSUE THREAD

**Issue by MuZhou233** [hustcc/lint-md#52]
```shell
lint-md ./*
```
在 Windows 系统中使用该命令会报错
```shell
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'C:\[DirectoryPath]\*.md'
```
而同样的命令在 Linux 系统或 Windows Subsystem for Linux 中都会正常展开通配符。
这是我的配置错误还是一个 BUG ？

**Comment by hustcc** [comment]
我试了下我 window 电脑好像可以，你那可以提供更多信息吗？

**Comment by MuZhou233** [comment]
以下是完整的 shell 信息和 log 文件，另外虽然不知道是否有关系，我在同样的位置使用 [Prettier](https://prettier.io/) 加通配符路径时并没有遇到问题
```shell
$ npm start

> @ start C:\Users\muzhou\Documents\GitHub\muzhou233.github.io
> lint-md ./*.md

internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'C:\Users\muzhou\Documents\GitHub\muzhou233.github.io\*.md'
    at Object.statSync (fs.js:915:3)
    at isDirectory (C:\Users\muzhou\Documents\GitHub\muzhou233.github.io\node_modules\lint-md-cli\bin\helper\file.js:22:13)
    at Timeout._onTimeout (C:\Users\muzhou\Documents\GitHub\muzhou233.github.io\node_modules\lint-md-cli\bin\helper\file.js:43:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\muzhou\\Documents\\GitHub\\muzhou233.github.io\\*.md'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `lint-md ./*.md`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\muzhou\AppData\Roaming\npm-cache\_logs\2019-12-26T03_52_32_787Z-debug.log
```
[2019-12-26T03_52_32_787Z-debug.log](https://github.com/hustcc/lint-md/files/4001280/2019-12-26T03_52_32_787Z-debug.log)

**Comment by hustcc** [comment]
有没兴趣帮忙调试解决下，我估计要到一月初才能有空😂🤣

**Comment by MuZhou233** [comment]
如果有空的话我会尝试的，但是我对于这个问题怎么解决没有什么思路🤔

**Comment by hustcc** [comment]
看 log 已经到 file.js 这个文件了，大概率是 glob 这个的问题吧，是做文件通配符查找的模块。
